import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Card } from "~ui-toolkit/components/Card/Card";
import { Grid } from "~ui-toolkit/components/Grid/Grid";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!!!@@@!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.js</code>
        </p>

        <Grid>
          <Card title="Documentation" url="https://nextjs.org/docs">
            <p>Find in-depth information about Next.js features and API.</p>
          </Card>
          <Card title="Learn" url="https://nextjs.org/learn">
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </Card>
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
